# Generated by Django 2.1.2 on 2021-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_1_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目1_1 文字列'),
        ),
    ]
